"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_peach)\
$os\
$username\
[](bg:color_blue fg:color_peach)\
$directory\
[](fg:color_blue bg:color_mauve)\
$git_branch\
$git_status\
[](fg:color_mauve bg:color_lavender)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_lavender bg:color_overlay0)\
$docker_context\
$conda\
[](fg:color_overlay0 bg:color_surface0)\
$time\
[ ](fg:color_surface0)\
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
# Base colors
color_text = '#cdd6f4'      # Text
color_base = '#1e1e2e'      # Base
color_surface0 = '#313244'  # Surface0
color_overlay0 = '#6c7086'  # Overlay0

# Accent colors
color_lavender = '#b4befe'  # Lavender
color_blue = '#89b4fa'      # Blue
color_mauve = '#cba6f7'     # Mauve
color_peach = '#fab387'     # Peach
color_green = '#a6e3a1'     # Green
color_red = '#f38ba8'       # Red
color_yellow = '#f9e2af'    # Yellow
color_teal = '#94e2d5'      # Teal

[os]
disabled = false
style = "bg:color_peach fg:color_base"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

#[username]
#show_always = true
#style_user = "bg:color_orange fg:color_fg0"
#style_root = "bg:color_orange fg:color_fg0"
#format = '[ $user ]($style)'

[directory]
style = "fg:color_base bg:color_blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
#"Documents" = "󰈙"
#"Downloads" = ""
#"Music" = "󰝚"
#"Pictures" = ""
#"Programming" = "󰲋"
"~" = ""

[git_branch]
symbol = ""
style = "bg:color_mauve"
format = '[[ $symbol $branch ](fg:color_base bg:color_mauve)]($style)'

[git_status]
style = "bg:color_mauve"
format = '[[($all_status$ahead_behind )](fg:color_base bg:color_mauve)]($style)'

[nodejs]
symbol = ""
style = "bg:color_lavender"
format = '[[ $symbol( $version) ](fg:color_base bg:color_lavender)]($style)'

[c]
symbol = " "
style = "bg:color_lavender"
format = '[[ $symbol( $version) ](fg:color_base bg:color_lavender)]($style)'

[rust]
symbol = ""
style = "bg:color_lavender"
format = '[[ $symbol( $version) ](fg:color_base bg:color_lavender)]($style)'

[golang]
symbol = ""
style = "bg:color_lavender"
format = '[[ $symbol( $version) ](fg:color_base bg:color_lavender)]($style)'

[php]
symbol = ""
style = "bg:color_lavender"
format = '[[ $symbol( $version) ](fg:color_base bg:color_lavender)]($style)'

[java]
symbol = ""
style = "bg:color_lavender"
format = '[[ $symbol( $version) ](fg:color_base bg:color_lavender)]($style)'

[kotlin]
symbol = ""
style = "bg:color_lavender"
format = '[[ $symbol( $version) ](fg:color_base bg:color_lavender)]($style)'

[haskell]
symbol = ""
style = "bg:color_lavender"
format = '[[ $symbol( $version) ](fg:color_base bg:color_lavender)]($style)'

[python]
symbol = ""
style = "bg:color_lavender"
format = '[[ $symbol( $version) ](fg:color_base bg:color_lavender)]($style)'

[docker_context]
symbol = ""
style = "bg:color_overlay0"
format = '[[ $symbol( $context) ](fg:color_text bg:color_overlay0)]($style)'

[conda]
style = "bg:color_overlay0"
format = '[[ $symbol( $environment) ](fg:color_text bg:color_overlay0)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_surface0"
format = '[[  $time ](fg:color_text bg:color_surface0)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:color_green)'
error_symbol = '[❯](bold fg:color_red)'
vimcmd_symbol = '[❮](bold fg:color_green)'
vimcmd_replace_one_symbol = '[❮](bold fg:color_mauve)'
vimcmd_replace_symbol = '[❮](bold fg:color_mauve)'
vimcmd_visual_symbol = '[❮](bold fg:color_yellow)'
